title: CS Connect Pk
markdown: kramdown
permalink: /blog/:title/
# permalink: /:year/:month/:day/:title/
# permalink: pretty

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: "<!--more-->"

# Collections
collections:
  posts:
    output: true
  events:
    output: false
    sort_by: date

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # author: "Talha Asghar"
  -
    scope:
      path: ""
      type: "events"
    values:
      author: "CS Connect PK Team"

# baseurl: "/website"
# url: "https://csconnectpk.github.io"
baseurl: "/csconnectpk"
url: "https://higgsboson909.github.io"

